import { useState } from 'react';
import { GraphSchema, type Graph } from '@codegraph/shared';
import { GraphViewer } from './GraphViewer';
import { Sidebar } from './Sidebar';
import { ThemeToggle } from './ThemeToggle';
import { UploadCloud } from 'lucide-react';

function App() {
  const [graph, setGraph] = useState<Graph | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [selectedNodeId, setSelectedNodeId] = useState<string | null>(null);
  const [searchQuery, setSearchQuery] = useState('');

  const loadExample = async () => {
    try {
      const res = await fetch('/example.json');
      const data = await res.json();
      const parsed = GraphSchema.parse(data);
      setGraph(parsed);
      setError(null);
    } catch (e: unknown) {
      setError('Failed to load example: ' + (e as Error).message);
    }
  };

  const handleFileUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    try {
      const text = await file.text();
      const data = JSON.parse(text);
      const parsed = GraphSchema.parse(data);
      setGraph(parsed);
      setError(null);
    } catch (e: unknown) {
      setError('Invalid graph file: ' + (e as Error).message);
    }
  };

  return (
    <div className="flex h-screen w-screen bg-background text-foreground overflow-hidden">
      {!graph ? (
        <div className="flex flex-col items-center justify-center w-full h-full space-y-6">
          <h1 className="text-4xl font-bold">CodeGraph Viewer</h1>
          <p className="text-muted-foreground text-center max-w-md">
            Upload a graph.json file generated by the CodeGraph CLI to explore your codebase architecture.
          </p>
          <div className="flex flex-col items-center gap-4">
            <label className="cursor-pointer bg-primary text-primary-foreground px-6 py-3 rounded-md flex items-center gap-2 hover:bg-primary/90 transition-colors">
              <UploadCloud className="w-5 h-5" />
              <span>Select graph.json</span>
              <input type="file" className="hidden" accept=".json" onChange={handleFileUpload} />
            </label>
            <div className="text-sm text-muted-foreground">or</div>
            <button onClick={loadExample} className="text-primary hover:underline">
              Load Soroban Example Graph
            </button>
          </div>
          {error && <div className="text-destructive bg-destructive/10 p-4 rounded-md max-w-lg">{error}</div>}
        </div>
      ) : (
        <>
          <Sidebar 
            graph={graph} 
            selectedNodeId={selectedNodeId} 
            searchQuery={searchQuery}
            setSearchQuery={setSearchQuery}
          />
          <div className="flex-1 relative h-full">
            <GraphViewer 
              graph={graph} 
              selectedNodeId={selectedNodeId}
              onNodeSelect={setSelectedNodeId}
              searchQuery={searchQuery}
            />
            <div className="absolute top-4 right-4 z-10 flex flex-col gap-2 items-end pointer-events-none">
              <div className="pointer-events-auto flex items-center gap-2 bg-card p-2 rounded-lg border shadow-sm">
                <ThemeToggle />
                <button onClick={() => setGraph(null)} className="text-sm px-3 py-1 bg-secondary text-secondary-foreground rounded hover:bg-secondary/80">
                  Close
                </button>
              </div>
              <div className="bg-card/90 backdrop-blur text-xs p-3 rounded-lg border shadow-sm pointer-events-auto max-w-xs">
                <p className="font-semibold mb-1">Honesty Note</p>
                <p className="text-muted-foreground text-[10px] leading-relaxed">
                  Static analysis only. Calls whose target is decided at runtime may appear unresolved.
                </p>
              </div>
            </div>
          </div>
        </>
      )}
    </div>
  );
}

export default App;
